<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="mb-4"><?= $this->translate('caption.sign_in') ?></h1>

        <?php if ($this->error): ?>
            <div class="alert alert-danger"
                 role="alert"><?= $this->error ?></div>
        <?php endif ?>

        <?= $this->form ?>

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col text-right">
            <dl>
                <dt>Username:</dt>
                <dd><tt>bruce</tt> …oder… <tt>clark</tt></dd>
            </dl>
        </div>
        <div class="col">
            <dl>
                <dt>Password:</dt>
                <dd><tt>test1234</tt></dd>
            </dl>
        </div>
    </div>
</div>
